### Demo Read

GET {{baseUrl}}/demo-read
Authorization: {{authTokenType}} {{authToken}}

### Demo Write

GET {{baseUrl}}/demo-write
Authorization: {{authTokenType}} {{authToken}}


### Demo User Info

GET {{baseUrl}}/user-info
Authorization: {{authTokenType}} {{authToken}}

