### Pre-flight check

OPTIONS {{baseUrl}}/demo-read
Origin: http://localhost:8082
Access-Control-Request-Method: GET

### Demo Read

GET {{baseUrl}}/demo-read
Authorization: {{authTokenType}} {{authToken}}

### Demo Write

GET {{baseUrl}}/demo-write
Authorization: {{authTokenType}} {{authToken}}


### Demo User Info

GET {{baseUrl}}/user-info
Authorization: {{authTokenType}} {{authToken}}

