version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
#    ports:
#      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.2
    command: start-dev
#    command: 'start
#      --optimized
#      --hostname localhost
#      --https-certificate-file=/etc/x509/https/keycloak.crt
#      --https-certificate-key-file=/etc/x509/https/keycloak.key'
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
#      - "8443:8443"
#    volumes:
#      - ./data/keycloak/ssl:/etc/x509/https:ro
